title: Dark Data Zine # Title of site.
timezone: USA/Berlin

sass:
  sass_dir: _sass
  style: :compressed

permalink: :title

markdown: kramdown

kramdown:
  input: GFM
  html_to_native: true
  syntax_highlighter: rouge

collections:
  articles:
    permalink: :title
    output: true

defaults:
  - scope:
      type: "articles"
    values:
      layout: "article"
